update-mobility-resources-info:
  scheduler-cron: 0/30 * * * * ?
get-info-mobility-resources:
  host: https://apidev.meep.me/tripplan/api/v1
  path: /routers/{location}/resources?lowerLeftLatLon={lowerLeftLatLon}&upperRightLatLon={upperRightLatLon}&companyZoneIds={companyZoneIds}

mobility:
  params:
    location: lisboa
    lowerLeftLatLon:
      - 38.711046
      - -9.160096
    upperRightLatLon:
      - 38.739429
      - -9.137115
    companyZoneIds:
      - 545
      - 467
      - 473

mobilityresource:
  exchange: mobilityresource_exchange
  updated:
    key: mobilityresource.updated